[Challenge #1] Média de Alunos
he4rtlabs/he4rtoberfest-2020 pull request #107
Opened 2020-10-05 19:58 UTC by jayron88

2020-10-05 20:02 UTC, jonatasosilva approved these changes

2020-10-05 21:30 UTC, baka-noob requested changes
Que tal um desafio maior? você pode pedir o input do usuário, ao invés de definir os valores das notas você mesmo.

2020-10-05 23:41 UTC, evertoont approved these changes

2020-10-06 02:29 UTC, jayron88 commented
> Que tal um desafio maior? você pode pedir o input do usuário, ao invés de definir os valores das notas você mesmo.

Feito.

2020-10-06 04:02 UTC, baka-noob approved these changes

2020-10-06 20:53 UTC, merged