Finalizando o desafio
he4rtlabs/he4rtoberfest-2020 pull request #129
Opened 2020-10-05 20:56 UTC by cristopherpds

2020-10-05 22:54 UTC, Luisnadachi approved these changes

2020-10-05 23:11 UTC, Luisnadachi requested changes
Salve cristopherpds!

Só preciso que você copie e cole o "model.md" para a pasta com o seu nick, coloque suas infos e altere o nome para "readme.md"

2020-10-05 23:59 UTC, cristopherpds commented
@Luisnadachi deu ruim aqui, dushaudhsau tem como remover tudo meu ai, comecar do 0

2020-10-06 00:09 UTC, Logikoz requested changes
Show primo!
![image](https://user-images.githubusercontent.com/37851168/95144410-385e4100-073e-11eb-96f0-e1821ecd8628.png)

Agora só falta criar o **.gitignore** dentro da sua pasta /chistopherds.
De preferencia, usar o github para fazer isso, e seleciona o modelo do VisualStudio, assim ele vai ignorar os itens certinho!

Veja aqui: 
![image](https://user-images.githubusercontent.com/37851168/95144362-16fd5500-073e-11eb-9a0d-cd0d7f420f72.png)

2020-10-06 00:29 UTC, closed without merging