[Challenge #2] Tabuada
he4rtlabs/he4rtoberfest-2020 pull request #181
Opened 2020-10-05 23:41 UTC by GuilhermeSouza01

2020-10-05 23:55 UTC, wallmartins requested changes
Salve, primo, tudo tranquilo?

Preciso que você exclua os arquivos que não pertencem a esse desafio, deixando nessa PR somente os arquivos referentes ao challenge #2. Por favor, realize essa mudança para que a gente possa analisar a sua PR e aprová-la, caso tudo mais esteja correto.

2020-10-06 00:00 UTC, GuilhermeSouza01 commented
@wallmartins Pronto primo exclui os arquivos, você poderia me dar uma ajuda, para quando eu criar uma nova branch, não vir os commits anteriores?

2020-10-06 00:22 UTC, wallmartins commented
Então, primo, você precisa copiar os arquivos atuais, depois você dá git checkout na master para, após realizar isso, você cria a nova branch para o novo desafio, assim você não puxará os arquivos do desafio anterior.

Ou seja, toda vez que for iniciar um desafio novo, você tem que realizar esse processo de dar checkout na master e realizar op processo do novo desafio.

2020-10-06 00:27 UTC, GuilhermeSouza01 commented
@wallmartins entendi primo, muito obrigado pela ajuda, vou fazer as mudanças!

2020-10-06 00:47 UTC, closed without merging