Finalizando o desafio 2
he4rtlabs/he4rtoberfest-2020 pull request #197
Opened 2020-10-06 00:21 UTC by GuilhermeAureliano

2020-10-06 00:23 UTC, wallmartins requested changes
Salve, primo, tudo bem?

Preciso que você exclua todos os arquivos que não forem correspondentes com o desafio 2 ao qual essa PR corresponde. Todos os PR's precisam ter somente o arquivo que realiza o desafio e o readme dele. Assim que fizer isso, poderemos realizar o review e aprovação, caso tudo esteja certo.

2020-10-06 00:28 UTC, GuilhermeAureliano commented
Acho que agora deu certo. Removi tudo que não tinha nada a ver com o desafio.

2020-10-06 00:37 UTC, Logikoz requested changes

2020-10-06 00:37 UTC, Logikoz commented on challenges/2-tabuada/java/guilhermeaureliano/README.md
> +**Twitter**: --
Remove isso aqui primo, já que não preencheu! 😅

2020-10-06 00:37 UTC, Logikoz commented on challenges/2-tabuada/java/guilhermeaureliano/README.md
> +**Comentários:** --
Aqui também

2020-10-06 00:43 UTC, GuilhermeAureliano commented on challenges/2-tabuada/java/guilhermeaureliano/README.md
> +**Comentários:** --
No do twitter eu deixei sem nada porque eu não tenho. Mas vou adicionar comentários.

2020-10-06 14:59 UTC, Logikoz commented
@GuilhermeAureliano a ideia é que caso vc não preencha os campos opcionais, exclua-os.

Então se vc não tem twitter, basta remover o campo, não precisa dizer que não tem!

Edita ai primo, fico no aguardo!

2020-10-06 15:00 UTC, Logikoz requested changes

2020-10-06 15:00 UTC, Logikoz commented on challenges/2-tabuada/java/guilhermeaureliano/README.md
> +**Twitter**: Não tenho.
@GuilhermeAureliano a ideia é que caso vc não preencha os campos opcionais, exclua-os.

Então se vc não tem twitter, basta remover o campo, não precisa dizer que não tem!

Edita ai primo, fico no aguardo!

2020-10-07 00:07 UTC, GuilhermeAureliano commented
Não entendi qual o conflito que está dando, primo. Poderia me dá uma luz?

2020-10-07 00:33 UTC, closed without merging