Finalizando o desafio
he4rtlabs/he4rtoberfest-2020 pull request #285
Opened 2020-10-06 13:25 UTC by ArtToledo

2020-10-06 14:22 UTC, franciscocandido requested changes
Esqueceu de declarar a variável `nota2`.
Sem ela o código não vai funcionar, corrige isso ai por favor.

2020-10-06 14:23 UTC, arthurzeras approved these changes

2020-10-06 14:26 UTC, arthurzeras commented
> Esqueceu de declarar a variável `nota2`.
> Sem ela o código não vai funcionar, corrige isso ai por favor.

@franciscocandido opa, na verdade tá declarada sim as duas, porém ele usou uma forma "minificada" de declaração usando a vírgula pra separar as variaveis. Testei aqui e funcionou normalmente. 😄

2020-10-06 14:30 UTC, franciscocandido commented
> > Esqueceu de declarar a variável `nota2`.
> > Sem ela o código não vai funcionar, corrige isso ai por favor.
> 
> @franciscocandido opa, na verdade tá declarada sim as duas, porém ele usou uma forma "minificada" de declaração usando a vírgula pra separar as variaveis. Testei aqui e funcionou normalmente.

Realmente. Não prestei atenção na vírgula.

2020-10-06 14:33 UTC, franciscocandido approved these changes

2020-10-06 14:35 UTC, ArtToledo commented
Isso mesmo @arthurzeras, valeu por aprovar @franciscocandido😄

2020-10-07 00:02 UTC, wallmartins requested changes
Salve, primo, tudo bem?

Uma pequena modificação, já que não está errado, ele funciona no navegador, mas dentro de uma IDE não está mostrando o resultado, então você poderia colocar um console.log dentro da função, na parte do cáculo, ou na chamada da função, isso faria ele mostrar nas duas situações e dar o resultado para todas as pessoas que testassem o programa, mesmo sendo iniciante.

2020-10-07 00:30 UTC, merged