Desafio 4 - Cifra de César
he4rtlabs/he4rtoberfest-2020 pull request #338
Opened 2020-10-06 20:46 UTC by brenu

2020-10-06 23:07 UTC, brenu commented
@wallmartins , uma dúvida: Eu preciso mudar o título do PR para que ele fique nesse formato sempre? Notei que sempre acabam mudando o nome dele aqui.

2020-10-06 23:13 UTC, baka-noob commented
> @wallmartins , uma dúvida: Eu preciso mudar o título do PR para que ele fique nesse formato sempre? Notei que sempre acabam mudando o nome dele aqui.
Você pode mudar mas os colaboradores já estão fazendo isso também.

2020-10-07 04:41 UTC, Logikoz requested changes
Show primo, só coloca uma mensagens pra mostrar pro usuário os passos, como está lá no readme do desafio.

também só mostra o resultado quando o usuário informar todos os dados.

2020-10-07 04:45 UTC, baka-noob reviewed
Olá brenu, seu código está correto, porém quando digito em letras minusculas ele apresenta alguns erros, que tal melhorar seu desafio e fazer o script entender letras minusculas também?

2020-10-07 10:52 UTC, brenu commented
@baka-noob certinho, vou fazer isso. @Logikoz , Eu não entendi direito como seriam as mensagens mas vou tentar. Se ficar ruim me avisa de novo.

2020-10-07 15:23 UTC, Logikoz commented
> @baka-noob certinho, vou fazer isso. @Logikoz , Eu não entendi direito como seriam as mensagens mas vou tentar. Se ficar ruim me avisa de novo.

Não houve nenhuma mudança no seu código, verifica se commitou.

2020-10-07 15:29 UTC, brenu commented
Modifiquei de maneira que ele armazenasse todos os possíveis resultados antes de imprimir na tela, mas...isso tem um potencial de falha de segmentação enorme, já que o enunciado menciona ser o número de casos de teste um tipo INT, e o maior INT é 2147483647. Isso multiplicado por 50 que é o tamanho de cada string resulta num potencial de mais de 100GB de memória alocada.

2020-10-07 19:32 UTC, Logikoz reviewed
As mensagens que eu me referi, era sobre os inputs, tipo:

Informe o texto:
informe a quantidade de letras a ser deslocadas.: 

só pra ficar mais iterativo pro usuário.

2020-10-07 19:59 UTC, Logikoz approved these changes
Perfeito!

2020-10-07 20:00 UTC, merged