[Challenge #3] Área de um trapézio
he4rtlabs/he4rtoberfest-2020 pull request #343
Opened 2020-10-06 21:16 UTC by vitox320

2020-10-06 22:00 UTC, franciscocandido requested changes
Faltou lembrar da compilação no README

2020-10-07 00:37 UTC, wallmartins requested changes

2020-10-07 00:37 UTC, wallmartins commented on challenges/3-area-trapezio/java/waaz/Trapezio.java
> +			return (baseMaior + baseMenor) * (altura / 2);
Salve, primo, tudo tranquilo?

A sua fórmula para o cálculo do trapézio foi escrita de forma incorreta, visto que você precisa que todos os valores, da base maior, da base menor e da altura sejam divididos por dois no final, sendo assim, envolver a operação de divisão com a altura, você faz com que só essa variável seja dividida por 2, e depois pegue o resultado dessa operação e multiplique pelo resultado que deu da outra operação dentro dos parenteses, dando um valor incorreto.

Tirando por essa questão, acredito que o restante está funcionando corretamente.

2020-10-07 01:04 UTC, vitox320 commented on challenges/3-area-trapezio/java/waaz/Trapezio.java
> +			return (baseMaior + baseMenor) * (altura / 2);
Salve primo!! Entendi sim, já fiz as alterações

2020-10-07 01:06 UTC, wallmartins approved these changes

2020-10-07 01:06 UTC, wallmartins commented on challenges/3-area-trapezio/java/waaz/Trapezio.java
> +			return (baseMaior + baseMenor) * (altura / 2);
Agora sim, funcionando corretamente.

2020-10-07 01:07 UTC, merged