[Challenge #2] Tabuada
he4rtlabs/he4rtoberfest-2020 pull request #36
Opened 2020-10-05 03:51 UTC by evertoont

2020-10-05 04:27 UTC, Logikoz requested changes
Só um desafio por branch primo, remove o media de aluno.

de preferencia, cria seu branch a partir da master, e não do outro branch.

2020-10-05 18:39 UTC, evertoont commented
> Só um desafio por branch primo, remove o media de aluno.
> 
> de preferencia, cria seu branch a partir da master, e não do outro branch.

Acabei me passando nesse detalhe aqui também, mas já realizei a alteração. Thanks!

2020-10-05 19:25 UTC, DanielHe4rt commented
Primo, boa tarde!

Como já mergeamos o desafio 0, você não pode apagar o arquivo pois ele vai interpretar que você não quer mais ele na branch principal.

Volta o desafio 0 agora, por gentileza.

2020-10-05 20:13 UTC, evertoont commented
> Primo, boa tarde!
> 
> Como já mergeamos o desafio 0, você não pode apagar o arquivo pois ele vai interpretar que você não quer mais ele na branch principal.
> 
> Volta o desafio 0 agora, por gentileza.

Boa tarde!

Creio que agora está correto, dei um revert no ultimo commit e deixei o desafio 0.

2020-10-06 00:25 UTC, he4rtlabs commented
Resolva o conflito antes de prosseguir, por favor.

2020-10-06 00:28 UTC, Logikoz approved these changes
Perfeito!

2020-10-06 00:54 UTC, closed without merging