[Challenge #1] Média de alunos
he4rtlabs/he4rtoberfest-2020 pull request #404
Opened 2020-10-07 01:41 UTC by mpgxc

2020-10-07 02:34 UTC, baka-noob requested changes
Olá, tentei digitar letras para quebrar seu código e ele mesmo assim funcionou e fez o cálculo! dá uma olhadinha, não está errado pois ele não considera a letra, mas que tal pedir ao usuário para digitar novamente?

2020-10-07 07:32 UTC, Logikoz reviewed
Boa madrugada primo! O quê você acha de fazer um plus pra esse desafio? Se você puder ter infinitas notas para fazer essa média, como você faria? Caso também o usuário colocar algum tipo de informação não numérica dentro da sua aplicação, como ela se portaria?

Caso você queira o desafio, tá ai uma boa pedida. Porém caso você não quiser, me sinaliza no post para que eu possa mergear o PR!

2020-10-07 16:34 UTC, mpgxc commented
Opa, Boa tarde, vou refatorar.

2020-10-07 21:23 UTC, baka-noob requested changes
Ola mpgxc, seu código compilou porém apresenta erro de execução, tentei em máquinas diferentes e nada, rever!

2020-10-07 23:38 UTC, mpgxc commented
Saquei, vou verificar isso. vlw :)

2020-10-08 19:15 UTC, baka-noob approved these changes

2020-10-08 19:15 UTC, merged