[Challenge #8] Fibonacci
he4rtlabs/he4rtoberfest-2020 pull request #411
Opened 2020-10-07 02:07 UTC by DanteBorges

2020-10-07 03:56 UTC, baka-noob requested changes
Olá DanteBorges, seu desafio está certo porém não corresponde 100% ao que é pedido no desafio. O algoritmo precisa ser um número menor do que 46, aguardo modificação para que eu possa aprovar o PR.

2020-10-07 21:37 UTC, DanteBorges commented
Código editado

2020-10-07 21:50 UTC, baka-noob requested changes
Olá DanteBorges, seu desafio está certo porém não corresponde 100% ao que é pedido no desafio. O algoritmo precisa ser um número maior do que 0, aguardo modificação para que eu possa aprovar o PR.

2020-10-08 01:35 UTC, DanteBorges commented
Código atualizado

2020-10-08 01:45 UTC, baka-noob approved these changes

2020-10-08 01:45 UTC, merged