[Challenge #7] valida senha
he4rtlabs/he4rtoberfest-2020 pull request #414
Opened 2020-10-07 02:11 UTC by DanteBorges

2020-10-07 03:29 UTC, baka-noob requested changes
Você enviou o desafio errado. A branch e o nome estão como desafio 7 mas o script é o desafio 1, rever!

2020-10-07 03:50 UTC, DanteBorges commented
código editado

2020-10-07 03:51 UTC, DanteBorges commented
editado

Em qua., 7 de out. de 2020 às 00:29, Bárbara Gualberto <
notifications@github.com> escreveu:

> *@baka-noob* requested changes on this pull request.
>
> Você enviou o desafio errado. A branch e o nome estão como desafio 7 mas o
> script é o desafio 1, rever!
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/he4rtlabs/he4rtoberfest-2020/pull/414#pullrequestreview-503500178>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ANLEQVMOXQXURR5LHQOB7JLSJPOBPANCNFSM4SGY5E3Q>
> .
>

2020-10-07 04:08 UTC, baka-noob requested changes
A sintaxe do seu código está errada, rever!

2020-10-07 07:37 UTC, Logikoz requested changes
Primo, parece que vc tacou um tradutor durante esse processo ai, e subiu o código erro de sintaxe.

corrige ai pra gente!

2020-10-07 21:23 UTC, DanteBorges commented
Código corrigido

2020-10-07 21:28 UTC, baka-noob reviewed
Senti falta de um break caso a senha fosse valida, porem como não foi especificado no desafio, tudo bem!

2020-10-07 21:28 UTC, baka-noob approved these changes

2020-10-09 05:00 UTC, Logikoz approved these changes

2020-10-09 05:00 UTC, merged