[Challenge #0] Hello World
he4rtlabs/he4rtoberfest-2020 pull request #45
Opened 2020-10-05 04:32 UTC by godinhojoao

A pedido de um primo, renomeei a pasta do desafio e estou dando PR novamente.

2020-10-05 05:23 UTC, Logikoz requested changes
Obrigado pela correção das pastas!

Mas vc excluiu o readme.md do hello world, e não pode fazer isso.
pois esse arquivo é a base para os próximos participantes levarem para desenvolver seus desafios!

Por favor, desfaça essa exclusão  😊

2020-10-05 20:14 UTC, godinhojoao commented
@Logikoz adicionei novamente mano, foi mal e muito obrigado!

2020-10-05 21:40 UTC, wallmartins requested changes
Salve, godinhojoao, tudo bem?

Então, primo, o arquivo que você pegou e enviou como readme não tem a descrição correta, você copia o MODEL.MD, cola ele dentro da pasta do seu desafio, nesse caso, do desafio 0, renomeia ele para README.MD e preenche as partes de texto dele para as suas infos, aquelas que quiser colocar.

2020-10-05 23:30 UTC, godinhojoao commented
@wallmartins salve! Não é isso mano? 
![image](https://user-images.githubusercontent.com/66435387/95142252-9e03fa80-0749-11eb-9edc-bf80831848b1.png)

2020-10-06 00:31 UTC, Logikoz commented
@godinhojoao o dan já havia corrigido isso, mas obrigado!

2020-10-06 00:31 UTC, closed without merging