[Challenges #4] Cifra de César
he4rtlabs/he4rtoberfest-2020 pull request #490
Opened 2020-10-07 22:36 UTC by Clerijr

Preciso tanto de um psiquiatra quanto de um emprego

2020-10-07 23:10 UTC, Logikoz requested changes
O exercício não foi resolvido.

1. falta a validação do tamanho da string de entrada, máximo 50 caracteres.
2. falta a validação do numero de deslocamento das letras (0 <= N <= 25)
3. falta a entrada da quantidade de casos a ser feito, se for 3 por exemplo, deve executar o seu código atual 3 vezes, e por ai vai.

2020-10-07 23:10 UTC, Logikoz commented on challenges/3-area-trapezio/python/clerijr/readme.md
> +se quiser sair, digitar 'sair', caso contrário, pressionar enter
Como foi só uma edição de texto, está ok.
da pra aceitar!

2020-10-07 23:15 UTC, baka-noob requested changes
Clerijr, algumas coisas a considerar no seu script:
- Evite usar vírgulas em python, mesmo que opicional, é uma boa prática não usar.
- Seu código não corresponde 100% ao que é pedido no desafio, faltou o input de numero de casos.
- Quando escrevo inputs de letra minuscula o código apresenta alguns erros, que tal aceitar letras minusculas do usuário?

2020-10-08 00:24 UTC, baka-noob commented
> Clerijr, algumas coisas a considerar no seu script:
> 
>     * Evite usar vírgulas em python, mesmo que opicional, é uma boa prática não usar.
> 
>     * Seu código não corresponde 100% ao que é pedido no desafio, faltou o input de numero de casos.
> 
>     * Quando escrevo inputs de letra minuscula o código apresenta alguns erros, que tal aceitar letras minusculas do usuário?

Você fez algumas mudanças mas o código ainda não reconhece letras minusculas.

2020-10-08 00:33 UTC, Clerijr commented
@baka-noob perdão pela falta de experiência, mas pode especificar exatamente oq não reconhece? aqui eu testei e funfou 
![image](https://user-images.githubusercontent.com/67716586/95401860-b5c3b600-08e4-11eb-94a7-e290f55cd951.png)

2020-10-08 00:35 UTC, baka-noob commented
> @baka-noob perdão pela falta de experiência, mas pode especificar exatamente oq não reconhece? aqui eu testei e funfou
> ![image](https://user-images.githubusercontent.com/67716586/95401860-b5c3b600-08e4-11eb-94a7-e290f55cd951.png)

tentei escrever barbara com letras minusculas e apareceu um acento.

2020-10-08 00:50 UTC, Clerijr commented
ahhhh blz tô vendo aqui, vou arrumar

2020-10-08 01:27 UTC, baka-noob approved these changes

2020-10-08 04:31 UTC, Logikoz approved these changes
Perfeito!

2020-10-08 04:31 UTC, merged