Desafio 1
he4rtlabs/he4rtoberfest-2020 pull request #516
Opened 2020-10-08 11:13 UTC by feliper2002

2020-10-08 18:09 UTC, baka-noob requested changes
Olá feliper2002, seu desafio contem alguns erros. 
- Ao digitar as duas notas nada acontece, peço que reveja o programa.
- O comando utilzado no bash dá erro, normalmente para programas em C++ utilizamos g++ nomedoprograma.cpp -o nomedoprograma && ./nomedoprograma.

2020-10-08 19:20 UTC, feliper2002 commented
Corrigido.

2020-10-09 04:58 UTC, Logikoz reviewed
Boa madrugada primo! O quê você acha de fazer um plus pra esse desafio? Se você puder ter infinitas notas para fazer essa média, como você faria? Caso também o usuário colocar algum tipo de informação não numérica dentro da sua aplicação, como ela se portaria?

Caso você queira o desafio, tá ai uma boa pedida. Porém caso você não quiser, me sinaliza no post para que eu possa mergear o PR!

2020-10-09 06:24 UTC, baka-noob approved these changes

2020-10-09 11:31 UTC, feliper2002 commented
Bom dia, Logikoz. Andei pesquisando formas de chegar a essa finalidade do desafio, mas não consegui encontrar alguma maneira. No entanto, o que me veio em mente foi fazer um loop while que tivesse a condição de != EOF (end of file) e usaria uma estrutura como a lista, por exemplo, ou até mesmo um array do vector para ir guardando os valores para no final dividir a soma de todas as notas pelo tamanho da estrutura/array (no final digitava um valor negativo para dar um break no loop, por exemplo). A questão é que não sei como fazer esta implementação para vários valores informados em apenas uma linha.

2020-10-10 01:11 UTC, DanielHe4rt approved these changes

2020-10-10 02:08 UTC, closed without merging