[Challenge #1] Média de alunos
he4rtlabs/he4rtoberfest-2020 pull request #518
Opened 2020-10-08 13:23 UTC by mlg404

2020-10-08 13:25 UTC, mlg404 commented
Acabei esquecendo de dar o pull depois que finalizei o desafio 0 e o enviei novamente por engano.
Deseja que eu envie novamente ou está tudo bem?

2020-10-08 14:29 UTC, arthurabreu00 requested changes
JS Funcional é muito daora, parabéns.

2020-10-08 14:29 UTC, arthurabreu00 commented on challenges/0-hello-world/js/mlg404/readme.md
> +**Exercicio:** 0 - Hello World
Acredito que este readme.md , não deveria pertencer a este PR.

2020-10-09 05:12 UTC, Logikoz requested changes
Lembre-se de sempre criar a branch a partir da SUA MASTER para nao vir itens de outros desafios em PR diferente!

por favor, corrigir o arquivo do desafio 0.

2020-10-09 09:58 UTC, mlg404 commented
Se eu retirar esse arquivo e commitar já funciona ou tem outra maneira de resolver?

2020-10-09 10:51 UTC, mlg404 reviewed
Resolvido!
Foi bom ter dado esse erro, aprendi a reverter um commit errado! Obrigado!

2020-10-10 02:08 UTC, arthurabreu00 approved these changes

2020-10-10 12:49 UTC, Logikoz approved these changes
Perfeito!

2020-10-10 12:50 UTC, merged