[Challenge #1] Média dos Alunos
he4rtlabs/he4rtoberfest-2020 pull request #54
Opened 2020-10-05 12:07 UTC by RafaelaMicaela

2020-10-05 17:00 UTC, Logikoz requested changes
Altera o nome da pasta de **1** para **1-media-alunos** para seguir com o padrão primo

2020-10-05 19:44 UTC, DanielHe4rt commented
Boa tarde prima! O quê você acha de fazer um plus pra esse desafio? Se você puder ter infinitas notas para fazer essa média, como você faria? Caso você queira o desafio, tá ai uma boa pedida. Porém caso você não quiser, me sinaliza no post para que eu possa mergear o PR!

2020-10-05 23:08 UTC, he4rtlabs commented
@RafaelaMicaela boa noite! 

Acho que você esqueceu de trocar a pasta do outro arquivo também. 
challenges/challenges/1-media-alunos/js/MediaDeAlunos.js` para a pasta correta

2020-10-05 23:31 UTC, he4rtlabs commented
Prima, seguinte. 

Ó, vamo lá. A ideia é que seus arquivos fique dentro da pasta `challenge/1-media-alunos/js/RafaelaMicaela/` entendeu? Qualquer coisa me marca aqui que eu já te ajudo caso sobrarem dúvidas.

2020-10-05 23:34 UTC, RafaelaMicaela commented
@he4rtlabs  No caso esse 'MediaDeAlunos.js' apago ?

2020-10-05 23:39 UTC, he4rtlabs commented
Crie uma  pasta com o seu nome no diretório como o exemplo ao lado -> `challenges/1-media-alunos/js/RafaelaMicaela/` 

Após isso, mova seus arquivos .js e .md para essa pasta (lembrando que você renomeou o arquivo de markdown para JS, sendo que ele deve ser .md) e vamos ver o que acontece.

2020-10-06 00:10 UTC, RafaelaMicaela commented
![image](https://user-images.githubusercontent.com/33203072/95144436-0d301d80-074f-11eb-807e-5d635f91a0e1.png)

não sei o que tô fazendo de errado .-.

2020-10-06 00:35 UTC, he4rtlabs approved these changes

2020-10-06 00:36 UTC, merged