adicionando resolucao de fibbonaci
he4rtlabs/he4rtoberfest-2020 pull request #541
Opened 2020-10-08 20:19 UTC by arthur-mts

2020-10-08 20:54 UTC, baka-noob requested changes
Ola arthur-mts, você não seguiu 100% o desafio, o input do usuário deve ser maior do que 0 e menor do que 46, aguardando modificação para aprovação!

2020-10-09 02:24 UTC, arthur-mts commented
Da uma olhada aí @baka-noob por favor!

2020-10-09 06:01 UTC, barbrina commented on challenges/8-fibonacci/python/arthur-mts/main.py
> +    res = "0"
Ao invés de mandar 0, mande uma mensagem de erro.

2020-10-09 06:01 UTC, baka-noob commented on challenges/8-fibonacci/python/arthur-mts/main.py
> +    if((n <= 1) or (n > 46)):
se n for menor igual a 0 ou n for maior igual a 46, retorna o erro.

2020-10-09 19:54 UTC, j4g3 requested changes
Seu código esta com erro na execução

2020-10-10 01:44 UTC, closed without merging