[Challenge #0] Hello He4rtoberfest
he4rtlabs/he4rtoberfest-2020 pull request #60
Opened 2020-10-05 13:04 UTC by SaLandini

Eu estou fazendo de novo esse PR, por garantia e limpeza de conciencia, já que eu não sei o que que aconteceu com o primeiro, eu só tenho um E-mail sobre e é isso

2020-10-05 17:16 UTC, Logikoz approved these changes

2020-10-05 17:20 UTC, Logikoz requested changes
Faz o ajuste ai primo!

2020-10-05 17:20 UTC, Logikoz commented on challenges/0-hello-world/r/SaLandin/README.md
> +**Nível Técnico:** - Estudante/Estagiário/Junior/Pleno/Senior - Estudante
Por favor, coloque apenas **Estudante** e remova os demais!

2020-10-05 21:20 UTC, SaLandini reviewed
Fiz a alteração

2020-10-05 21:20 UTC, SaLandini commented on challenges/0-hello-world/r/SaLandin/README.md
> +**Nível Técnico:** - Estudante/Estagiário/Junior/Pleno/Senior - Estudante
Ok, feito meu bom

2020-10-06 00:19 UTC, Logikoz approved these changes
Perfeito!

2020-10-06 00:20 UTC, merged