[Challenge #1] Media dos alunos
he4rtlabs/he4rtoberfest-2020 pull request #62
Opened 2020-10-05 13:56 UTC by SaLandini

-- eu não sei o que que acontenceu nesse PR --

2020-10-05 17:21 UTC, Logikoz requested changes
Somente um desafio por PR primo.

Tira os itens do outro desafio e também adiciona o readme no desafio dos alunos!

2020-10-05 21:17 UTC, SaLandini reviewed
@Logikoz, eu removi os arquivos do desafio 0

2020-10-06 00:18 UTC, Logikoz requested changes
Ainda está faltando o readme do desafio, por favor adicione!

2020-10-06 01:31 UTC, SaLandini commented
Ok, amanhã eu adiciono

2020-10-06 13:40 UTC, SaLandini commented
@Logikoz, feito!

2020-10-06 17:15 UTC, closed without merging