[Challenges #1] Média de alunos
he4rtlabs/he4rtoberfest-2020 pull request #63
Opened 2020-10-05 14:04 UTC by AkiraTorres

2020-10-05 16:32 UTC, Hakawa2 commented on challenges/1-media-alunos/js/akiratorres/average.js
> +    return (average = (22 + 53) / 2);
Opa primo boa tarde tudo bem ? 
Aqui você acabou deixando as notas hardcoded, acredito que estava testando e acabou esquecendo de trocar pelos args

2020-10-05 16:34 UTC, wendelfreitas commented on challenges/1-media-alunos/js/akiratorres/average.js
> +    return (average = (22 + 53) / 2);
@AkiraTorres Muito bem, mas por que você não passou as variáveis `note1` e `note2` na soma?

2020-10-05 19:39 UTC, wallmartins commented
Salve, AkiraTorres, tudo tranquilo?

Em cada PR que enviar de cada desafio, sempre coloque, somente, o readme e o arquivo com o desafio, os arquivos dos desafios anteriores você deixa de fora, para as PR's de cada desafio mesmo.

Então preciso te pedir que você refaça esse PR e envie ele, somente, com o readme e o arquivo desse desafio em específico, que é o de média de alunos.

2020-10-05 23:26 UTC, Logikoz requested changes
Arruma esses problemas pra gente primo!

2020-10-06 01:44 UTC, AkiraTorres commented
Realizei as alterações pedidas, obrigado pela ajuda.

2020-10-06 19:33 UTC, merged