[Challenge #1] Media de alunos
he4rtlabs/he4rtoberfest-2020 pull request #88
Opened 2020-10-05 18:17 UTC by jpbrab0

2020-10-05 19:35 UTC, wallmartins commented
Salve, jpbrab0, tudo tranquilo?

Em cada PR que enviar de cada desafio, sempre coloque, somente, o readme e o arquivo com o desafio, os arquivos dos desafios anteriores você deixa de fora, para as PR's de cada desafio mesmo.

Então preciso te pedir que você refaça esse PR e envie ele, somente, com o readme e o arquivo desse desafio em específico, que é o de média de alunos.

2020-10-05 23:23 UTC, Logikoz requested changes
Arruma esses problemas ai pra gente primo!

2020-10-05 23:35 UTC, jpbrab0 commented
Não sei se ta certo agr, se tiver errado ainda é so falar q vou tentar corrigir.

2020-10-06 00:55 UTC, wallmartins commented
Segue com o erro de ter mais arquivos do que o que são os pedidos nessa PR. Você precisa apagar o readme e o hello-world dessa PR, porque ela está relacionada ao desafio 1 e não ao 0

2020-10-06 15:05 UTC, Logikoz requested changes
Segue os problemas citados anteriormente sobre a duplicidade de desafios.

Remova o desafio do hello world dessa branch.

Melhor ainda, sempre crie uma branch baseada na SUA MASTER quando for criar um desafio novo, para não acontecer esse problema!

2020-10-06 19:10 UTC, closed without merging