[Challenge #3] Área do trapézio
he4rtlabs/he4rtoberfest-2020 pull request #98
Opened 2020-10-05 19:36 UTC by jcesar0

2020-10-05 23:33 UTC, Logikoz approved these changes
Tudo certinho!

2020-10-05 23:37 UTC, he4rtlabs requested changes
Mudanças necessárias

2020-10-05 23:37 UTC, he4rtlabs commented on challenges/3-area-trapezio/php/jcesar/trapezio.php
> +    echo "INSERA 3 NÚMEROS POR FAVOR";
Primo, quando você foi dar output apenas em texto eu peço que você us aspas simples. Quando você usa aspas duplas, o PHP espera que você use alguma variável dentro para uso.

Porém, como você não está usando nada do tipo seria interessante seguir as boas práticas da PSR.

Também, trocar a palavra "INSERA" por "INSIRA" para melhor entendimento.

2020-10-06 00:58 UTC, he4rtlabs approved these changes

2020-10-06 00:58 UTC, merged